/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Thu Dec  1 19:35:14 2016. */

#include "AirSensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AirSensorMessage_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, AirSensorMessage, temperature, temperature, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, AirSensorMessage, humidity, temperature, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
