/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Fri Dec  2 21:13:15 2016. */

#include "AirSensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AirSensorMessage_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AirSensorMessage, deviceid, deviceid, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, AirSensorMessage, temperature, deviceid, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, AirSensorMessage, humidity, temperature, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
