/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8-dev at Fri Dec  2 21:13:15 2016. */

#ifndef PB_AIRSENSOR_PB_H_INCLUDED
#define PB_AIRSENSOR_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AirSensorMessage {
    int32_t deviceid;
    float temperature;
    float humidity;
/* @@protoc_insertion_point(struct:AirSensorMessage) */
} AirSensorMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AirSensorMessage_init_default            {0, 0, 0}
#define AirSensorMessage_init_zero               {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AirSensorMessage_deviceid_tag            1
#define AirSensorMessage_temperature_tag         2
#define AirSensorMessage_humidity_tag            3

/* Struct field encoding specification for nanopb */
extern const pb_field_t AirSensorMessage_fields[4];

/* Maximum encoded size of messages (where known) */
#define AirSensorMessage_size                    21

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define AIRSENSOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
